// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	ais_api "ais_service/internal/generated/grpc/ais_api"
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// AISServiceClient is an autogenerated mock type for the AISServiceClient type
type AISServiceClient struct {
	mock.Mock
}

// GetAisAccountByID provides a mock function with given fields: ctx, in, opts
func (_m *AISServiceClient) GetAisAccountByID(ctx context.Context, in *ais_api.GetAccountStatusRequest, opts ...grpc.CallOption) (*ais_api.GetAccountStatusResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetAisAccountByID")
	}

	var r0 *ais_api.GetAccountStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ais_api.GetAccountStatusRequest, ...grpc.CallOption) (*ais_api.GetAccountStatusResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ais_api.GetAccountStatusRequest, ...grpc.CallOption) *ais_api.GetAccountStatusResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ais_api.GetAccountStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ais_api.GetAccountStatusRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PublishAisAccount provides a mock function with given fields: ctx, in, opts
func (_m *AISServiceClient) PublishAisAccount(ctx context.Context, in *ais_api.PublishAisAccountRequest, opts ...grpc.CallOption) (*ais_api.PublishAisAccountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PublishAisAccount")
	}

	var r0 *ais_api.PublishAisAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ais_api.PublishAisAccountRequest, ...grpc.CallOption) (*ais_api.PublishAisAccountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ais_api.PublishAisAccountRequest, ...grpc.CallOption) *ais_api.PublishAisAccountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ais_api.PublishAisAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ais_api.PublishAisAccountRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAISServiceClient creates a new instance of AISServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAISServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AISServiceClient {
	mock := &AISServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
