// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeAISServiceServer is an autogenerated mock type for the UnsafeAISServiceServer type
type UnsafeAISServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedAISServiceServer provides a mock function with no fields
func (_m *UnsafeAISServiceServer) mustEmbedUnimplementedAISServiceServer() {
	_m.Called()
}

// NewUnsafeAISServiceServer creates a new instance of UnsafeAISServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeAISServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeAISServiceServer {
	mock := &UnsafeAISServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
